[colors.bright]
black = "#928374"
blue = "#83A598"
cyan = "#8EC07C"
green = "#B8BB26"
magenta = "#D3869B"
red = "#FB4934"
white = "#EBDBB2"
yellow = "#FABD2F"

[colors.normal]
black = "#504945"
blue = "#458588"
cyan = "#689D6A"
green = "#98971A"
magenta = "#B16286"
red = "#CC241D"
white = "#A89984"
yellow = "#D79921"

[colors.primary]
background = "#1A1A1A"
foreground = "#EBDBB2"

[colors.selection]
cursor = "#2C2C2C"
text = "CellForeground"
