# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 4000, host: 4000

  
  config.vm.synced_folder "files/", "/home/vagrant/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dev-vm"
    vb.memory = 4096
    vb.cpus = 2
  end
  
  config.vm.provision "shell", path: "bootstrap/update.sh"

end
